# Generated by Django 5.1.15 on 2026-01-15 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateImport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("separator", models.CharField(max_length=64)),
                ("restriction_enzyme", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="TemplateRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pid", models.CharField(max_length=128)),
                ("ptype", models.CharField(blank=True, max_length=128, null=True)),
                ("part_name", models.CharField(max_length=255)),
                (
                    "part_value",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "imp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="simulator.templateimport",
                    ),
                ),
            ],
        ),
    ]
