# Generated by Django 5.1.15 on 2026-01-18 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="templaterow",
            name="imp",
        ),
        migrations.DeleteModel(
            name="TemplateImport",
        ),
        migrations.DeleteModel(
            name="TemplateRow",
        ),
    ]
