# Generated by Django 5.1.15 on 2026-01-19 03:53

import django.db.models.deletion
import simulator.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=32, unique=True)),
                (
                    "template",
                    models.FileField(
                        blank=True, null=True, upload_to=simulator.models.job_upload_to
                    ),
                ),
                (
                    "preview",
                    models.FileField(
                        blank=True, null=True, upload_to=simulator.models.job_upload_to
                    ),
                ),
                (
                    "genbank_zip",
                    models.FileField(
                        blank=True, null=True, upload_to=simulator.models.job_upload_to
                    ),
                ),
                (
                    "mapping",
                    models.FileField(
                        blank=True, null=True, upload_to=simulator.models.job_upload_to
                    ),
                ),
                (
                    "outputs_zip",
                    models.FileField(
                        blank=True, null=True, upload_to=simulator.models.job_upload_to
                    ),
                ),
                ("status", models.CharField(default="RUNNING", max_length=10)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="simulator_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="JobInputFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("input", models.CharField(max_length=10)),
                ("file", models.FileField(upload_to=simulator.models.job_upload_to)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_files",
                        to="simulator.simulationjob",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="SimulationRun",
        ),
    ]
