# Generated by Django 5.1.15 on 2026-01-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationjob",
            name="outputs_dir",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
