# Generated by Django 5.1.15 on 2026-01-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SimulationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_id", models.CharField(max_length=32, unique=True)),
                ("status", models.CharField(default="RUNNING", max_length=10)),
                ("template_path", models.CharField(max_length=512)),
                ("genbank_path", models.CharField(max_length=512)),
                ("mapping_path", models.CharField(blank=True, max_length=512)),
                ("output_zip", models.CharField(blank=True, max_length=512)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="templaterow",
            name="imp",
        ),
        migrations.DeleteModel(
            name="TemplateImport",
        ),
        migrations.DeleteModel(
            name="TemplateRow",
        ),
    ]
