# Generated by Django 5.1.15 on 2026-01-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0002_simulationjob_jobinputfile_delete_simulationrun"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobinputfile",
            old_name="file",
            new_name="kind",
        ),
    ]
