# Generated by Django 5.1.15 on 2026-01-18 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0002_simulationrun_remove_templaterow_imp_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="simulationrun",
            old_name="output_zip",
            new_name="output_path",
        ),
        migrations.AddField(
            model_name="simulationrun",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
