# Generated by Django 5.1.15 on 2026-01-20 23:38

import simulator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0002_simulationjob_outputs_dir"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationjob",
            name="genbank_zip",
        ),
        migrations.RemoveField(
            model_name="simulationjob",
            name="mapping",
        ),
        migrations.RemoveField(
            model_name="simulationjob",
            name="outputs_dir",
        ),
        migrations.AlterField(
            model_name="simulationjob",
            name="preview",
            field=models.FileField(
                default="hey", upload_to=simulator.models.job_upload_to
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="simulationjob",
            name="template",
            field=models.FileField(upload_to=simulator.models.job_upload_to),
        ),
        migrations.DeleteModel(
            name="InputFile",
        ),
    ]
