# Generated by Django 5.1.15 on 2026-01-19 04:15

import simulator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0003_rename_file_jobinputfile_kind"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobinputfile",
            name="input",
        ),
        migrations.AddField(
            model_name="jobinputfile",
            name="file",
            field=models.FileField(
                default="l", upload_to=simulator.models.job_upload_to
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="jobinputfile",
            name="kind",
            field=models.CharField(max_length=10),
        ),
    ]
