# Generated by Django 5.1.15 on 2026-01-21 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0003_remove_simulationjob_genbank_zip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationjob",
            name="status",
            field=models.CharField(default="PENDING", max_length=10),
        ),
    ]
