# Generated by Django 5.1.15 on 2026-01-19 12:54

import django.db.models.deletion
import simulator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0004_remove_jobinputfile_input_jobinputfile_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InputFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_kind", models.CharField(max_length=10)),
                ("file", models.FileField(upload_to=simulator.models.job_upload_to)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="input_files",
                        to="simulator.simulationjob",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="JobInputFile",
        ),
    ]
