# Generated by Django 5.1.15 on 2026-01-18 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0004_alter_simulationrun_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationrun",
            name="genbank_path",
        ),
        migrations.RemoveField(
            model_name="simulationrun",
            name="mapping_path",
        ),
        migrations.RemoveField(
            model_name="simulationrun",
            name="template_path",
        ),
    ]
