# Generated by Django 5.1.15 on 2026-01-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0004_alter_simulationjob_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationjob",
            name="enzyme_name",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
