# Generated by Django 5.1.15 on 2026-01-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0005_remove_simulationrun_genbank_path_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationrun",
            name="output_path",
        ),
    ]
