# Generated by Django 5.2.11 on 2026-02-06 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0006_simulationjob_concentration_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationjob",
            name="enzyme_name",
        ),
    ]
