# Generated by Django 5.2.11 on 2026-02-06 18:08

import simulator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulator", "0007_remove_simulationjob_enzyme_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationjob",
            name="primers_file",
            field=models.FileField(
                blank=True, null=True, upload_to=simulator.models.job_upload_to
            ),
        ),
    ]
