# Generated by Django 5.2.11 on 2026-02-04 04:52

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("comment", models.TextField(blank=True, null=True)),
                ("creation_date", models.DateTimeField(verbose_name="Created At")),
                (
                    "separator",
                    models.CharField(
                        choices=[
                            (",", "Comma"),
                            ("-", "Hyphen"),
                            (".", "Dot"),
                            ("~", "Tilde"),
                            ("_", "Underscore"),
                            (":", "Colon"),
                            (";", "Semi-colon"),
                            ("/", "Slash"),
                            ("\\", "Backslash"),
                            ("'", "Apostrophe"),
                            ("=", "Equal"),
                            ("+", "Plus"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "restriction_enzyme",
                    models.CharField(
                        choices=[
                            ("BsaI", "BsaI"),
                            ("BsmBI", "BsmBI"),
                            ("BbsI", "BbsI"),
                            ("SapI", "SapI"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/Users/Cherif/projetweb2526/projet-web-G4/src/browse/public_data/assemblies"
                        ),
                        upload_to="",
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assemblies",
                        to="accounts.team",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InputParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=200)),
                ("typed", models.BooleanField(default=False)),
                ("mandatory", models.BooleanField(default=True)),
                (
                    "separator",
                    models.CharField(
                        blank=True,
                        choices=[
                            (",", "Comma"),
                            ("-", "Hyphen"),
                            (".", "Dot"),
                            ("~", "Tilde"),
                            ("_", "Underscore"),
                            (":", "Colon"),
                            (";", "Semi-colon"),
                            ("/", "Slash"),
                            ("\\", "Backslash"),
                            ("'", "Apostrophe"),
                            ("=", "Equal"),
                            ("+", "Plus"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("include_in_output_name", models.BooleanField(default=False)),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputparts_set",
                        to="browse.assembly",
                    ),
                ),
                ("allowed_types", models.ManyToManyField(blank=True, to="browse.type")),
            ],
        ),
    ]
