# Generated by Django 5.1.15 on 2026-01-20 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("comment", models.TextField(blank=True, null=True)),
                ("creation_date", models.DateTimeField(verbose_name="Created At")),
                (
                    "separator",
                    models.CharField(
                        choices=[
                            (",", "Comma"),
                            ("-", "Hyphen"),
                            (".", "Dot"),
                            ("~", "Tilde"),
                            ("_", "Underscore"),
                            (":", "Colon"),
                            (";", "Semi-colon"),
                            ("/", "Slash"),
                            ("\\", "Backslash"),
                            ("'", "Apostrophe"),
                            ("=", "Equal"),
                            ("+", "Plus"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "restriction_enzyme",
                    models.CharField(
                        choices=[
                            ("BsaI", "BsaI"),
                            ("BsmBI", "BsmBI"),
                            ("BbsI", "BbsI"),
                            ("SapI", "SapI"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="InputParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=200)),
                ("typed", models.BooleanField(default=False)),
                ("mandatory", models.BooleanField(default=True)),
                (
                    "separator",
                    models.CharField(
                        blank=True,
                        choices=[
                            (",", "Comma"),
                            ("-", "Hyphen"),
                            (".", "Dot"),
                            ("~", "Tilde"),
                            ("_", "Underscore"),
                            (":", "Colon"),
                            (";", "Semi-colon"),
                            ("/", "Slash"),
                            ("\\", "Backslash"),
                            ("'", "Apostrophe"),
                            ("=", "Equal"),
                            ("+", "Plus"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inputparts_set",
                        to="browse.assembly",
                    ),
                ),
                ("allowed_types", models.ManyToManyField(blank=True, to="browse.type")),
            ],
        ),
    ]
