# Generated by Django 5.1.15 on 2026-02-05 15:01

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\user\\Desktop\\Projet_web\\projet-web-G4\\src\\browse\\public_data\\assemblies'), upload_to=''),
        ),
    ]
