# Generated by Django 5.1.15 on 2026-01-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0002_remove_assembly_file_name_assembly_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="inputparts",
            name="include_in_output_name",
            field=models.BooleanField(default=False),
        ),
    ]
