# Generated by Django 5.1.15 on 2026-01-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0003_inputparts_include_in_output_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projet-web-G4/src/browse/public_data/browse",
            ),
        ),
    ]
