# Generated by Django 5.1.15 on 2026-02-08 13:40

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_alter_assembly_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='type',
            options={'ordering': ['type_name']},
        ),
        migrations.AlterField(
            model_name='assembly',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\user\\Desktop\\test_project\\projet-web-G4\\src\\browse\\public_data\\assemblies'), upload_to=''),
        ),
    ]
