# Generated by Django 5.1.15 on 2026-01-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0004_alter_assembly_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assemblies/'),
        ),
    ]
