# Generated by Django 5.2.11 on 2026-02-08 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0005_alter_assembly_file"),
        ("browse", "0006_alter_assembly_file"),
    ]

    operations = []
