# Generated by Django 5.1.15 on 2026-01-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0006_alter_assembly_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="src/browse/public_data/assemblies/"
            ),
        ),
    ]
