# Generated by Django 5.1.15 on 2026-02-02 21:56

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("browse", "0016_alter_assembly_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=django.core.files.storage.FileSystemStorage(
                    location="/Users/Cherif/projetweb2526/projet-web-G4/src/browse/public_data/assemblies"
                ),
                upload_to="",
            ),
        ),
    ]
