# Generated by Django 5.1.15 on 2026-02-03 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_adminrequest_mapping_alter_adminrequest_request_type'),
        ('browse', '0020_alter_assembly_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assemblies', to='accounts.team'),
        ),
    ]
