# Generated by Django 5.2.11 on 2026-02-04 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("browse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminrequest",
            name="assembly",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="browse.assembly",
            ),
        ),
    ]
