<<<<<<< HEAD
# Generated by Django 5.1.15 on 2026-02-02 20:30
=======
# Generated by Django 5.1.15 on 2026-02-02 18:20
>>>>>>> d947369c7baa7d0df2f627991a6a4ade5587c170

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_adminrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminrequest",
            name="admin_message",
            field=models.TextField(
                blank=True, help_text="Reason given by admin when rejecting"
            ),
        ),
    ]
