# Generated by Django 5.1.15 on 2026-02-02 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_adminrequest_processed_by'),
        ('browse', '0018_alter_assembly_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browse.assembly'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='request_type',
            field=models.CharField(choices=[('MAKE_COLLECTION_PUBLIC', 'Make collection public'), ('MAKE_ASSEMBLY_PUBLIC', 'Make assembly public')], max_length=50),
        ),
    ]
