# Generated by Django 5.1.15 on 2026-02-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_adminrequest_assembly_and_more'),
        ('plasmids', '0003_mappingtable'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrequest',
            name='mapping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plasmids.mappingtable'),
        ),
        migrations.AlterField(
            model_name='adminrequest',
            name='request_type',
            field=models.CharField(choices=[('MAKE_COLLECTION_PUBLIC', 'Make collection public'), ('MAKE_ASSEMBLY_PUBLIC', 'Make assembly public'), ('MAKE_MAPPING_TABLE_PUBLIC', 'Make mapping table public')], max_length=50),
        ),
    ]
