# Generated by Django 5.1.15 on 2026-02-01 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_team_teammembership"),
        ("plasmids", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="collections",
                to="accounts.team",
            ),
        ),
    ]
