# Generated by Django 5.1.15 on 2026-02-03 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plasmids', '0002_collection_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='MappingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mapping_path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapping_tables', to='plasmids.collection')),
            ],
        ),
    ]
