# Generated by Django 5.1.15 on 2026-01-07 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Assembly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("comment", models.TextField()),
                ("creation_date", models.DateTimeField(verbose_name="Created At")),
                ("separator", models.CharField(max_length=20)),
                ("restriction_enzyme", models.CharField(max_length=50)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="assemblies/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InputParts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("part_name", models.CharField(max_length=200)),
                ("optional", models.BooleanField(default=False)),
                ("mandatory", models.BooleanField(default=True)),
                ("separator", models.CharField(max_length=20)),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.assembly",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="assembly",
            name="input_parts",
            field=models.ManyToManyField(
                related_name="assemblies", to="campaigns.inputparts"
            ),
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_name", models.CharField(max_length=50)),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="campaigns.inputparts",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inputparts",
            name="allowed_types",
            field=models.ManyToManyField(
                related_name="input_parts", to="campaigns.type"
            ),
        ),
    ]
