# Generated by Django 5.1.15 on 2026-01-08 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assembly",
            name="input_parts",
        ),
        migrations.RemoveField(
            model_name="type",
            name="part",
        ),
        migrations.AlterField(
            model_name="inputparts",
            name="allowed_types",
            field=models.ManyToManyField(to="campaigns.type"),
        ),
        migrations.AlterField(
            model_name="inputparts",
            name="assembly",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inputparts_set",
                to="campaigns.assembly",
            ),
        ),
    ]
