# Generated by Django 5.1.15 on 2026-01-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_remove_assembly_input_parts_remove_type_part_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inputparts",
            old_name="optional",
            new_name="typed",
        ),
    ]
