# Generated by Django 5.1.15 on 2026-01-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0003_rename_optional_inputparts_typed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inputparts",
            name="allowed_types",
            field=models.ManyToManyField(blank=True, to="campaigns.type"),
        ),
        migrations.AlterField(
            model_name="inputparts",
            name="separator",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
