# Generated by Django 5.1.15 on 2026-01-10 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0004_alter_inputparts_allowed_types_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assembly",
            name="file",
        ),
        migrations.AddField(
            model_name="assembly",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
