# Generated by Django 5.1.15 on 2026-01-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_simulationrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="restriction_enzyme",
            field=models.CharField(
                choices=[
                    ("BsaI", "BsaI"),
                    ("BsmBI", "BsmBI"),
                    ("BbsI", "BbsI"),
                    ("SapI", "SapI"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="assembly",
            name="separator",
            field=models.CharField(
                choices=[
                    (",", "Comma"),
                    ("-", "Hyphen"),
                    (".", "Dot"),
                    ("~", "Tilde"),
                    ("_", "Underscore"),
                    (":", "Colon"),
                    (";", "Semi-colon"),
                    ("/", "Slash"),
                    ("\\", "Backslash"),
                    ("'", "Apostrophe"),
                    ("=", "Equal"),
                    ("+", "Plus"),
                ],
                max_length=20,
            ),
        ),
    ]
