# Generated by Django 5.1.15 on 2026-01-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0007_alter_assembly_restriction_enzyme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assembly",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="inputparts",
            name="separator",
            field=models.CharField(
                blank=True,
                choices=[
                    (",", "Comma"),
                    ("-", "Hyphen"),
                    (".", "Dot"),
                    ("~", "Tilde"),
                    ("_", "Underscore"),
                    (":", "Colon"),
                    (";", "Semi-colon"),
                    ("/", "Slash"),
                    ("\\", "Backslash"),
                    ("'", "Apostrophe"),
                    ("=", "Equal"),
                    ("+", "Plus"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
